### PR TITLE
fixed date formatting during export, added test assembly

### PR DESCRIPTION
**Pull request by gabornemeth**

### CODE REVIEW

**Comment by gabornemeth** [comment]
Hi @Fillius ,

Do you consider merging this PR?
Could you add license information for this project? If this is a "do whatever you'd like" type of project (Apache, MIT license), I would make some development on it, first of all make it portable.

Regards,
Gabor

**Comment by Fillius** [comment]
Hi Gabor,

Apologies for the late reply, it's been on my TODO list for a while, I've just been too busy.

Apache Licence is a good fit for this. I originally put it on Github for others to use and develop in the hope that someone could get a working Polar-Fitbit sync that they would share so I could use it on a daily basis.

I have since re-written this project as a Java web-app which synchronises in the background but I haven't had chance to do much with that.

Polar have just enabled syncing with MyFitnessPal on their Flow app (Android coming soon) but as far as I can tell (I don't have an iPhone to test) it syncs food stats to Polar, not heart rate/calories burned to MFP.

I look forward to seeing your changes, especially regarding portability.

**Comment by gjermshus** [comment]
Hi!
Thanks for a good project that saved me some time!
I used your project for my own Polarpersonaltrainer.com to RunKeeper sync application. I added support for extracting heart beats as well. Created a PR for that change.

**Comment by gjermshus** [comment]
Be carefull with the date formating the url for listing exercises. ppt.com is not culture invariant. So the correct formatting on lookup dates are decided by the users profile settings. If you use the date format dd.mm.yyyy and tthe user has yyyy-mm-dd as her preffered format, it will not work.

**Comment by gabornemeth** [comment]
Hi @gjermshus,

Thank you for the info. I'm going to review and fix it.
I'm working on a portable version, which also exports all the recorded heart rate, cadence and speed values also. It's going to be available in a few days.

**Comment by gabornemeth** [comment]
I have commited my changes to my fork. Please review it, and if you'd like, I make a PR.

**Comment by gjermshus** [comment]
Any plans for exporting GPX data? I need that as well, so I'm going to take a look at that soon

**Comment by gabornemeth** [comment]
Do you mean exporting GPS coordinates for the exercise also? If you can provide me some test account on PPT, I can implement that as well. The user whose account I have access does not have GPS equipment for her watch, so I don't have sample data.
It would be useful to make a consistent base, which all of us can work with. My last development is a bigger one, a lot of things have changed. I'm going to maintain this portable version for sure, because I use it for a cross platform app.

**Comment by Fillius** [comment]
You don't need a GPS compatible device, if you have and Android or iOS phone. The Polar Flow app can work without a heart rate monitor connected and collects GPS. I'm assuming it's in the same format as the GPS enabled devices.

**Comment by gabornemeth** [comment]
Thanks. I'll take a look at this.

**Comment by Fillius** [comment]
Actually I just checked, it's the Polar Beat app, not Flow.

**Comment by gjermshus** [comment]
What do you need? I can provide you with a GPX file exported from PPT.com. 
I have done some research on how ppt.com handles files. Users can export multiple traning sessions in one xml file. But GPX-files (gpx is the format used) can only be a single exercise in one file. ppt.com allows download of multiple gpx files but its then delivered as a zip archeive. There is no indication on the training list view on ppt.com wheter there exists gps-data for the traning session. The id of the traning session, used on ppt.com is only used on the site, its not available in any of the exported files.

The best solution seems to be that instead of downloading multiple training sessions, this system should download single document with the gpx file attached. So the function could return a ViewModel containing to Xml documents.

**Comment by gabornemeth** [comment]
I'm gonna check Polar Beat. I need access to a PPT account where exercises are recorded with GPS positions. If I can achieve this with my current account using Polar Beat on my Android device, than I can do some tests and likely implement this feature.

**Pull request merged**
